version: "3.8"

services:
  debezium:
    image: debezium/connect:latest
    container_name: debezium
    hostname: debezium
    ports:
      - "8083:8083"
    expose:
      - "29092"
    extra_hosts:
      - "host.docker.internal:192.168.1.18"  
    environment:
      BOOTSTRAP_SERVERS: broker:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: debezium
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      # KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      # VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:9081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:9081
      ENABLE_DEBEZIUM_SCRIPTING: 'true'
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail","-X", "GET", "http://debezium:8083/connectors"]

      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  debezium-ui:
    image: debezium/debezium-ui:latest
    container_name: debezium-ui
    hostname: debezium-ui
    ports:
      - '9082:8080'
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      - backend

networks:
  backend:
    external: true