version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres:14.1-alpine
    hostname: pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./data:/tmp/