"""add key field

Revision ID: d310602bede8
Revises: 9627a8c618ba
Create Date: 2024-04-24 09:57:12.123354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd310602bede8'
down_revision: Union[str, None] = '9627a8c618ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activation_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activation_key')
    # ### end Alembic commands ###
