"""add description and complete column

Revision ID: 3b689f2862c6
Revises: 2a160ed1fdc3
Create Date: 2024-04-29 09:51:44.063947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b689f2862c6'
down_revision: Union[str, None] = '2a160ed1fdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
