"""delete unique attr from user_id task table

Revision ID: a7c8e752927c
Revises: 6a8ef7cf5e08
Create Date: 2024-04-30 16:08:10.763245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c8e752927c'
down_revision: Union[str, None] = '6a8ef7cf5e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index('ix_tasks_user_id', 'tasks', ['user_id'], unique=True)
    # ### end Alembic commands ###
